# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/aspnet-mvc"

# The destination folder where Jekyll will write the site files
destination: _site-mvc

# Exclude files which should not be in the output
exclude: [README.md,
Gemfile,
Gemfile.lock,
api_sort.rb,
Dockerfile,
bs-config.js,
build-docs.sh,
copy_content.sh,
copy_local.sh,
docs-watcher/*,
exclude_files.txt,
install-npm.sh,
start-docs.sh,
watch.sh,
migration/*,
tutorials/tutorial-kendo-music-store/*,
tutorials/tutorial-saleshub/*,
tag-helpers/*,
getting-started-core/*,
backwards-compatibility/2018-backwards-compatibility.md,
knowledge-base/checkbox-list-post.md,
knowledge-base/daterangepicker-bind-to-model-and-post.md,
knowledge-base/daterangepicker-messages-input-text-change.md,
knowledge-base/form-in-strongly-typed-view.md,
knowledge-base/grid-add-new-button-header-inline.md,
knowledge-base/grid-ajax-binding.md,
knowledge-base/grid-ajax-editing.md,
knowledge-base/grid-bind-a-dropdownlist-editor.md,
knowledge-base/grid-custom-datasource-razor-pages.md,
knowledge-base/grid-custom-datasource.md,
knowledge-base/grid-enable-operations-for-object-column.md,
knowledge-base/grid-header-multicolumn-title-change.md,
knowledge-base/grid-icon-command-button-no-text.md,
knowledge-base/grid-is-not-showing-data.md,
knowledge-base/grid-listbox-as-editor.md,
knowledge-base/grid-multiselect-as-editor.md,
knowledge-base/grid-norecords-template-controller-server-viewdata.md,
knowledge-base/grid-page-size-all.md,
knowledge-base/grid-remove-spinner-numerictextbox-editor.md,
knowledge-base/invalid-template-error-when-using-localization.md,
knowledge-base/multiselect-post-data-values.md,
knowledge-base/scheduler-sql-server-database.md,
knowledge-base/setup-private-nuget-feed-azure.md,
knowledge-base/treelist-checkbox-column.md,
knowledge-base/upload-resize-image-before-upload.md,
knowledge-base/validator-basic-form-validation.md,
knowledge-base/vs-online-continuous-integration-login-problem.md]

exclude_navigation: ["knowledge-base/*",
api/Kendo.Mvc/*,
api/Kendo.Mvc.UI/*,
api/Kendo.Mvc.UI.Fluent/*,
asp-net-mvc-3.html,
asp-net-mvc-4.html,
getting-started-mvc/*]

## The application virtual path
baseurl: /aspnet-mvc

ff-sheet-id: 17DDhsKyPUgO6GlvL8WEfCCN6tikyInp4qpRGCvvs794

## Product
product_long: "Progress Telerik UI for ASP.NET MVC"
product: "Telerik UI for ASP.NET MVC"
product_short: "UI for ASP.NET MVC"
framework: "ASP.NET MVC"
framework_short: "MVC"
platform: aspnet-mvc

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"
        product: "aspnet-mvc"
        editable: true
        title_prefix: "MVC"
-
    scope:
        path: "aspnet-mvc"
    values:
        product: "aspnet-mvc"
-
    scope:
        path: "api"
    values:
        editable: false
        res_type: api
        kind: api
-
    scope:
        path: "html-helpers/barcodes/barcode"
    values:
        title_prefix: "MVC BarCode Component"
-
    scope:
        path: "html-helpers/barcodes/qrcode"
    values:
        title_prefix: "MVC QRCode Component"
-
    scope:
        path: "html-helpers/charts"
    values:
        title_prefix: "MVC Chart Component"
-
    scope:
        path: "html-helpers/conversational-ui/chat"
    values:
        title_prefix: "MVC Chat Component"
-
    scope:
        path: "html-helpers/data-management/filemanager"
    values:
        title_prefix: "MVC FileManager Component"
-
    scope:
        path: "html-helpers/data-management/filter"
    values:
        title_prefix: "MVC Filter Component"
-
    scope:
        path: "html-helpers/data-management/grid"
    values:
        title_prefix: "MVC Data Grid Component"
-
    scope:
        path: "html-helpers/data-management/listview"
    values:
        title_prefix: "MVC ListView Component"
-
    scope:
        path: "html-helpers/data-management/pivotgrid"
    values:
        title_prefix: "MVC PivotGrid Component"
-
    scope:
        path: "html-helpers/data-management/spreadsheet"
    values:
        title_prefix: "MVC Spreadsheet Component"
-
    scope:
        path: "html-helpers/data-management/treelist"
    values:
        title_prefix: "MVC TreeList Component"
-
    scope:
        path: "html-helpers/datasource"
    values:
        title_prefix: "MVC Data Source Component"
-
    scope:
        path: "html-helpers/diagrams-and-maps/diagram"
    values:
        title_prefix: "MVC Diagram Component"
-
    scope:
        path: "html-helpers/diagrams-and-maps/map"
    values:
        title_prefix: "MVC Map Component"
-
    scope:
        path: "html-helpers/editors/autocomplete"
    values:
        title_prefix: "MVC AutoComplete Component"
-
    scope:
        path: "html-helpers/editors/colorpalette"
    values:
        title_prefix: "MVC ColorPalette Component"
-
    scope:
        path: "html-helpers/editors/colorpicker"
    values:
        title_prefix: "MVC ColorPicker Component"
-
    scope:
        path: "html-helpers/editors/combobox"
    values:
        title_prefix: "MVC ComboBox Component"
-
    scope:
        path: "html-helpers/editors/dateinput"
    values:
        title_prefix: "MVC DateInput Component"
-
    scope:
        path: "html-helpers/editors/datepicker"
    values:
        title_prefix: "MVC DatePicker Component"
-
    scope:
        path: "html-helpers/editors/daterangepicker"
    values:
        title_prefix: "MVC DateRangePicker Component"
-
    scope:
        path: "html-helpers/editors/datetimepicker"
    values:
        title_prefix: "MVC DateTimePicker Component"
-
    scope:
        path: "html-helpers/editors/dropdownlist"
    values:
        title_prefix: "MVC DropDownList Component"
-
    scope:
        path: "html-helpers/editors/dropdowntree"
    values:
        title_prefix: "MVC DropDownTree Component"
-
    scope:
        path: "html-helpers/editors/editor"
    values:
        title_prefix: "MVC Editor Component"
-
    scope:
        path: "html-helpers/editors/flatcolorpicker"
    values:
        title_prefix: "MVC FlatColorPicker Component"
-
    scope:
        path: "html-helpers/editors/listbox"
    values:
        title_prefix: "MVC ListBox Component"
-
    scope:
        path: "html-helpers/editors/maskedtextbox"
    values:
        title_prefix: "MVC MaskedTextBox Component"
-
    scope:
        path: "html-helpers/editors/multicolumncombobox"
    values:
        title_prefix: "MVC MultiColumnComboBox Component"
-
    scope:
        path: "html-helpers/editors/multiselect"
    values:
        title_prefix: "MVC MultiSelect Component"
-
    scope:
        path: "html-helpers/editors/numerictextbox"
    values:
        title_prefix: "MVC NumericTextBox Component"
-
    scope:
        path: "html-helpers/editors/rating"
    values:
        title_prefix: "MVC Rating Component"
-
    scope:
        path: "html-helpers/editors/slider"
    values:
        title_prefix: "MVC Slider Component"
-
    scope:
        path: "html-helpers/editors/switch"
    values:
        title_prefix: "MVC Switch Component"
-
    scope:
        path: "html-helpers/editors/timepicker"
    values:
        title_prefix: "MVC TimePicker Component"
-
    scope:
        path: "html-helpers/editors/upload"
    values:
        title_prefix: "MVC Upload Component"
-
    scope:
        path: "html-helpers/editors/validator"
    values:
        title_prefix: "MVC Validator Component"
-
    scope:
        path: "html-helpers/gauges/arcgauge"
    values:
        title_prefix: "MVC ArcGauge Component"
-
    scope:
        path: "html-helpers/gauges/lineargauge"
    values:
        title_prefix: "MVC LinearGauge Component"
-
    scope:
        path: "html-helpers/gauges/radialgauge"
    values:
        title_prefix: "MVC RadialGauge Component"
-
    scope:
        path: "html-helpers/hybrid"
    values:
        title_prefix: "MVC Hybrid"
-
    scope:
        path: "html-helpers/interactivity/draganddrop"
    values:
        title_prefix: "MVC DragAndDrop Component"
-
    scope:
        path: "html-helpers/interactivity/progressbar"
    values:
        title_prefix: "MVC ProgressBar Component"
-
    scope:
        path: "html-helpers/interactivity/sortable"
    values:
        title_prefix: "MVC Sortable Component"
-
    scope:
        path: "html-helpers/layout/badge"
    values:
        title_prefix: "MVC Badge Component"
-
    scope:
        path: "html-helpers/layout/dialog"
    values:
        title_prefix: "MVC Dialog Component"
-
    scope:
        path: "html-helpers/layout/notification"
    values:
        title_prefix: "MVC Notification Component"
-
    scope:
        path: "html-helpers/layout/popup"
    values:
        title_prefix: "MVC Popup Component"
-
    scope:
        path: "html-helpers/layout/responsivepanel"
    values:
        title_prefix: "MVC ResponsivePanel Component"
-
    scope:
        path: "html-helpers/layout/splitter"
    values:
        title_prefix: "MVC Splitter Component"
-
    scope:
        path: "html-helpers/layout/tooltip"
    values:
        title_prefix: "MVC Tooltip Component"
-
    scope:
        path: "html-helpers/layout/window"
    values:
        title_prefix: "MVC Window Component"
-
    scope:
        path: "html-helpers/media/mediaplayer"
    values:
        title_prefix: "MVC MediaPlayer Component"
-
    scope:
        path: "html-helpers/media/scrollview"
    values:
        title_prefix: "MVC ScrollView Component"
-
    scope:
        path: "html-helpers/navigation/breadcrumb"
    values:
        title_prefix: "MVC Breadcrumb Component"
        title: "Breadcrumb"
-       
    scope:
        path: "html-helpers/navigation/button"
    values:
        title_prefix: "MVC Button Component"
-
    scope:
        path: "html-helpers/navigation/buttongroup"
    values:
        title_prefix: "MVC ButtonGroup Component"
-
    scope:
        path: "html-helpers/navigation/drawer"
    values:
        title_prefix: "MVC Drawer Component"
-
    scope:
        path: "html-helpers/navigation/menu"
    values:
        title_prefix: "MVC Menu Component"
-
    scope:
        path: "html-helpers/navigation/panelbar"
    values:
        title_prefix: "MVC PanelBar Component"
-
    scope:
        path: "html-helpers/navigation/radiobutton"
    values:
        title_prefix: "MVC RadioButton Component"
-
    scope:
        path: "html-helpers/navigation/tabstrip"
    values:
        title_prefix: "MVC TabStrip Component"
-
    scope:
        path: "html-helpers/navigation/timeline"
    values:
        title_prefix: "MVC TimeLine Component"
-
    scope:
        path: "html-helpers/navigation/toolbar"
    values:
        title_prefix: "MVC ToolBar Component"
-
    scope:
        path: "html-helpers/navigation/treeview"
    values:
        title_prefix: "MVC TreeView Component"
-
    scope:
        path: "html-helpers/pdf/pdfviewer"
    values:
        title_prefix: "MVC PDFViewer Component"
-
    scope:
        path: "html-helpers/scheduling/calendar"
    values:
        title_prefix: "MVC Calendar Component"
-
    scope:
        path: "html-helpers/scheduling/gantt"
    values:
        title_prefix: "MVC Gantt Component"
-
    scope:
        path: "html-helpers/scheduling/multiviewcalendar"
    values:
        title_prefix: "MVC MultiViewCalendar Component"
-
    scope:
        path: "html-helpers/scheduling/scheduler"
    values:
        title_prefix: "MVC Scheduler Component"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

# The google services configuration
google_tag_manager: GTM-6X92
gcs_engine: '001595215763381649090:rdwxfmavt8o'
gcs_api_key: 'AIzaSyDnvT29LoZiLUcywskEgTTum7j5pkx6s8I'

core: false
mvc: true

footer:
-
  title: "Getting Started"
  links:
    "Getting Started": https://docs.telerik.com/aspnet-mvc/getting-started/first-steps
    "Demos": https://demos.telerik.com/aspnet-mvc/
    "Sample Applications": https://demos.telerik.com/aspnet-mvc/
-
  title: "Support Resources"
  links:
    "Knowledge Base": https://docs.telerik.com/aspnet-mvc/knowledge-base
-
  title: "Community"
  links:
    "Forums": https://www.telerik.com/forums/aspnet-mvc
    "Blogs": https://www.telerik.com/blogs/.net
    "Feedback Portal": https://feedback.telerik.com/aspnet-mvc


download: http://www.telerik.com/download/aspnet-mvc
