# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/aspnet-mvc"

# The destination folder where Jekyll will write the site files
destination: _site-mvc

# Exclude files which should not be in the output
exclude: [README.md,
Gemfile,
Gemfile.lock,
api_sort.rb,
Dockerfile,
bs-config.js,
build-docs.sh,
copy_content.sh,
copy_local.sh,
deployment/*,
docs-watcher/*,
exclude_files.txt,
install-npm.sh,
start-docs.sh,
watch.sh,
migration/*,
troubleshoot/troubleshooting-net5.md,
tutorials/tutorial-kendo-music-store/*,
tutorials/tutorial-saleshub/*,
tag-helpers/*,
getting-started-core/*,
backwards-compatibility/2018-backwards-compatibility.md,
installation/*,
compatibility/*,
document-processing.md,
knowledge-base/checkbox-list-post.md,
knowledge-base/daterangepicker-bind-to-model-and-post.md,
knowledge-base/daterangepicker-messages-input-text-change.md,
knowledge-base/form-in-strongly-typed-view.md,
knowledge-base/grid-add-new-button-header-inline.md,
knowledge-base/grid-ajax-binding.md,
knowledge-base/grid-ajax-editing.md,
knowledge-base/grid-bind-a-dropdownlist-editor.md,
knowledge-base/grid-custom-datasource-razor-pages.md,
knowledge-base/grid-custom-datasource.md,
knowledge-base/grid-dynamic-popup-editing.md,
knowledge-base/grid-dynamic.md,
knowledge-base/grid-editing-upload-in-popup,
knowledge-base/grid-enable-operations-for-object-column.md,
knowledge-base/grid-header-multicolumn-title-change.md,
knowledge-base/grid-icon-command-button-no-text.md,
knowledge-base/grid-is-not-showing-data.md,
knowledge-base/grid-listbox-as-editor.md,
knowledge-base/grid-multiselect-as-editor.md,
knowledge-base/grid-norecords-template-controller-server-viewdata.md,
knowledge-base/grid-page-size-all.md,
knowledge-base/grid-remove-spinner-numerictextbox-editor.md,
knowledge-base/grid-toolbar-template.md,
knowledge-base/invalid-template-error-when-using-localization.md,
knowledge-base/multiselect-post-data-values.md,
knowledge-base/scheduler-sql-server-database.md,
knowledge-base/setup-private-nuget-feed-azure.md,
knowledge-base/treelist-checkbox-column.md,
knowledge-base/upload-resize-image-before-upload.md,
knowledge-base/validator-basic-form-validation.md,
knowledge-base/vs-online-continuous-integration-login-problem.md,
knowledge-base/grid-toggle-editable-mode.md,
html-helpers/data-management/filemanager/binding/razor-page.md,
html-helpers/datasource/razor-page.md,
html-helpers/conversational-ui/chat/razor-page.md,
html-helpers/editors/autocomplete/binding/razor-pages.md,
html-helpers/editors/checkboxgroup/razor-page.md,
html-helpers/editors/dropdownlist/binding/razor-page.md,
html-helpers/editors/colorpicker/razor-page.md,
html-helpers/editors/combobox/binding/razor-page.md,
html-helpers/editors/dropdowntree/binding/razor-page.md,
html-helpers/editors/multicolumncombobox/binding/razor-page.md,
html-helpers/editors/multiselect/binding/razor-page.md,
html-helpers/editors/radiogroup/razor-page.md,
html-helpers/editors/rating/razor-page.md,
html-helpers/editors/slider/razor-page.md,
html-helpers/editors/switch/razor-page.md,
html-helpers/editors/upload/razor-page.md,
html-helpers/editors/imageeditor/razor-page.md,
html-helpers/interactivity/loader/razor-page.md,
html-helpers/layout/form/razor-page.md,
html-helpers/layout/dialog/razor-page.md,
html-helpers/layout/notification/razor-page.md,
html-helpers/layout/splitter/razor-page.md,
html-helpers/layout/tooltip/razor-page.md,
html-helpers/layout/window/razor-page.md,
html-helpers/navigation/breadcrumb/razor-page.md,
html-helpers/navigation/button/razor-page.md,
html-helpers/navigation/buttongroup/razor-page.md,
html-helpers/navigation/menu/binding/razor-page.md,
html-helpers/navigation/menu/contextmenu/razor-page.md,
html-helpers/navigation/panelbar/binding/razor-page.md,
html-helpers/navigation/radiobutton/razor-page.md,
html-helpers/navigation/stepper/razor-page.md,
html-helpers/navigation/wizard/razor-page.md,
html-helpers/scheduling/scheduler/binding/razor-page.md,
html-helpers/scheduling/scheduler/binding/signalr-binding.md,
html-helpers/navigation/tabstrip/razor-page.md,
html-helpers/scheduling/calendar/razor-pages.md,
html-helpers/editors/datepicker/razor-pages.md,
html-helpers/editors/datetimepicker/razor-pages.md,
html-helpers/scheduling/multiviewcalendar/razor-pages.md,
html-helpers/charts/treemap/razor-pages.md,
html-helpers/navigation/toolbar/razor-page.md,
html-helpers/data-management/treelist/binding/razor-page.md,
html-helpers/editors/dateinput/razor-page.md,
html-helpers/editors/daterangepicker/razor-page.md,
html-helpers/navigation/drawer/razor-page.md,
html-helpers/pdf/pdfviewer/razor-page.md,
html-helpers/data-management/listview/binding/razor-page.md,
html-helpers/media/mediaplayer/razor-page.md,
html-helpers/overview-taghelpers]

exclude_navigation: ["knowledge-base/*",
api/Kendo.Mvc/*,
api/Kendo.Mvc.UI/*,
api/Kendo.Mvc.UI.Fluent/*,
asp-net-mvc-3.html,
asp-net-mvc-4.html,
getting-started-mvc/*]

## The application virtual path
baseurl: /aspnet-mvc

ff-sheet-id: 17DDhsKyPUgO6GlvL8WEfCCN6tikyInp4qpRGCvvs794

## Product
product_long: "Progress Telerik UI for ASP.NET MVC"
product: "Telerik UI for ASP.NET MVC"
product_short: "UI for ASP.NET MVC"
product_url: https://www.telerik.com/aspnet-mvc
framework: "ASP.NET MVC"
framework_short: "MVC"
platform: aspnet-mvc

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"
        product: "aspnet-mvc"
        editable: true
        title_prefix: "ASP.NET MVC"
        title_prefix_separator: " "
-
    scope:
        path: "aspnet-mvc"
    values:
        product: "aspnet-mvc"
-
    scope:
        path: "api"
    values:
        editable: false
        res_type: api
        kind: api
-
    scope:
        path: "integration-with-other-telerik-products"
    values:
        title_prefix: "Capture ASP.NET MVC"
-
    scope:
        path: "html-helpers/barcodes/barcode"
    values:
        title_prefix: "ASP.NET MVC BarCode Component"
-
    scope:
        path: "html-helpers/barcodes/qrcode"
    values:
        title_prefix: "ASP.NET MVC QRCode Component"
-
    scope:
        path: "html-helpers/charts"
    values:
        title_prefix: "ASP.NET MVC Chart Component"
-
    scope:
        path: "html-helpers/conversational-ui/chat"
    values:
        title_prefix: "ASP.NET MVC Chat Component"
-
    scope:
        path: "html-helpers/data-management/filemanager"
    values:
        title_prefix: "ASP.NET MVC FileManager Component"
-
    scope:
        path: "html-helpers/data-management/filter"
    values:
        title_prefix: "ASP.NET MVC Filter Component"
-
    scope:
        path: "html-helpers/data-management/grid"
    values:
        title_prefix: "ASP.NET MVC Data Grid Component"
-
    scope:
        path: "html-helpers/data-management/listview"
    values:
        title_prefix: "ASP.NET MVC ListView Component"
-
    scope:
        path: "html-helpers/data-management/pivotgrid"
    values:
        title_prefix: "ASP.NET MVC PivotGrid Component"
-
    scope:
        path: "html-helpers/data-management/pivotgridv2"
    values:
        title_prefix: "ASP.NET MVC PivotGridV2 Component"
-
    scope:
        path: "html-helpers/data-management/taskboard"
    values:
        title_prefix: "ASP.NET MVC TaskBoard Component"
-
    scope:
        path: "html-helpers/data-management/spreadsheet"
    values:
        title_prefix: "ASP.NET MVC Spreadsheet Component"
-
    scope:
        path: "html-helpers/data-management/treelist"
    values:
        title_prefix: "ASP.NET MVC TreeList Component"
-
    scope:
        path: "html-helpers/datasource"
    values:
        title_prefix: "ASP.NET MVC Data Source Component"
-
    scope:
        path: "html-helpers/diagrams-and-maps/diagram"
    values:
        title_prefix: "ASP.NET MVC Diagram Component"
-
    scope:
        path: "html-helpers/diagrams-and-maps/map"
    values:
        title_prefix: "ASP.NET MVC Map Component"
-
    scope:
        path: "html-helpers/diagrams-and-maps/orgchart"
    values:
        title_prefix: "ASP.NET MVC OrgChart Component"
-
    scope:
        path: "html-helpers/editors/autocomplete"
    values:
        title_prefix: "ASP.NET MVC AutoComplete Component"
-
    scope:
        path: "html-helpers/editors/checkboxgroup"
    values:
        title_prefix: "ASP.NET MVC CheckBoxGroup Component"
-
    scope:
        path: "html-helpers/editors/colorgradient"
    values:
        title_prefix: "ASP.NET MVC ColorGradient Component"
-
    scope:
        path: "html-helpers/editors/colorpalette"
    values:
        title_prefix: "ASP.NET MVC ColorPalette Component"
-
    scope:
        path: "html-helpers/editors/colorpicker"
    values:
        title_prefix: "ASP.NET MVC ColorPicker Component"
-
    scope:
        path: "html-helpers/editors/combobox"
    values:
        title_prefix: "ASP.NET MVC ComboBox Component"
-
    scope:
        path: "html-helpers/editors/captcha"
    values:
        title_prefix: "ASP.NET MVC Captcha Component"
-
    scope:
        path: "html-helpers/editors/dateinput"
    values:
        title_prefix: "ASP.NET MVC DateInput Component"
-
    scope:
        path: "html-helpers/editors/datepicker"
    values:
        title_prefix: "ASP.NET MVC DatePicker Component"
-
    scope:
        path: "html-helpers/editors/daterangepicker"
    values:
        title_prefix: "ASP.NET MVC DateRangePicker Component"
-
    scope:
        path: "html-helpers/editors/datetimepicker"
    values:
        title_prefix: "ASP.NET MVC DateTimePicker Component"
-
    scope:
        path: "html-helpers/editors/dropdownlist"
    values:
        title_prefix: "ASP.NET MVC DropDownList Component"
-
    scope:
        path: "html-helpers/editors/dropdowntree"
    values:
        title_prefix: "ASP.NET MVC DropDownTree Component"
-
    scope:
        path: "html-helpers/editors/editor"
    values:
        title_prefix: "ASP.NET MVC Editor Component"
-
    scope:
        path: "html-helpers/editors/flatcolorpicker"
    values:
        title_prefix: "ASP.NET MVC FlatColorPicker Component"
-
    scope:
        path: "html-helpers/editors/imageeditor"
    values:
        title_prefix: "ASP.NET MVC Image Editor Component"
-
    scope:
        path: "html-helpers/editors/listbox"
    values:
        title_prefix: "ASP.NET MVC ListBox Component"
-
    scope:
        path: "html-helpers/editors/maskedtextbox"
    values:
        title_prefix: "ASP.NET MVC MaskedTextBox Component"
-
    scope:
        path: "html-helpers/editors/multicolumncombobox"
    values:
        title_prefix: "ASP.NET MVC MultiColumnComboBox Component"
-
    scope:
        path: "html-helpers/editors/multiselect"
    values:
        title_prefix: "ASP.NET MVC MultiSelect Component"
-
    scope:
        path: "html-helpers/editors/numerictextbox"
    values:
        title_prefix: "ASP.NET MVC NumericTextBox Component"
-
    scope:
        path: "html-helpers/editors/rating"
    values:
        title_prefix: "ASP.NET MVC Rating Component"
-
    scope:
        path: "html-helpers/editors/radiogroup"
    values:
        title_prefix: "ASP.NET MVC RadioGroup Component"
-
    scope:
        path: "html-helpers/editors/slider"
    values:
        title_prefix: "ASP.NET MVC Slider Component"
-
    scope:
        path: "html-helpers/editors/switch"
    values:
        title_prefix: "ASP.NET MVC Switch Component"
-
    scope:
        path: "html-helpers/editors/textarea"
    values:
        title_prefix: "ASP.NET MVC TextArea Component"
-
    scope:
        path: "html-helpers/editors/textbox"
    values:
        title_prefix: "ASP.NET MVC TextBox Component"
-
    scope:
        path: "html-helpers/editors/timepicker"
    values:
        title_prefix: "ASP.NET MVC TimePicker Component"
-
    scope:
        path: "html-helpers/editors/upload"
    values:
        title_prefix: "ASP.NET MVC Upload Component"
-
    scope:
        path: "html-helpers/editors/validator"
    values:
        title_prefix: "ASP.NET MVC Validator Component"
-
    scope:
        path: "html-helpers/gauges/arcgauge"
    values:
        title_prefix: "ASP.NET MVC ArcGauge Component"
-
    scope:
        path: "html-helpers/gauges/circulargauge"
    values:
        title_prefix: "ASP.NET MVC CircularGauge Component"
-
    scope:
        path: "html-helpers/gauges/lineargauge"
    values:
        title_prefix: "ASP.NET MVC LinearGauge Component"
-
    scope:
        path: "html-helpers/gauges/radialgauge"
    values:
        title_prefix: "ASP.NET MVC RadialGauge Component"
-
    scope:
        path: "html-helpers/hybrid"
    values:
        title_prefix: "ASP.NET MVC Hybrid"
-
    scope:
        path: "html-helpers/interactivity/draganddrop"
    values:
        title_prefix: "ASP.NET MVC DragAndDrop Component"
-
    scope:
        path: "html-helpers/interactivity/loader"
    values:
        title_prefix: "ASP.NET MVC Loader Component"
-
    scope:
        path: "html-helpers/interactivity/skeletoncontainer"
    values:
        title_prefix: "ASP.NET MVC SkeletonContainer Component"
-
    scope:
        path: "html-helpers/interactivity/progressbar"
    values:
        title_prefix: "ASP.NET MVC ProgressBar Component"
-
    scope:
        path: "html-helpers/interactivity/circularprogressbar"
    values:
        title_prefix: "ASP.NET MVC Circular ProgressBar Component"
-
    scope:
        path: "html-helpers/interactivity/sortable"
    values:
        title_prefix: "ASP.NET MVC Sortable Component"
-
    scope:
        path: "html-helpers/layout/badge"
    values:
        title_prefix: "ASP.NET MVC Badge Component"
-
    scope:
        path: "html-helpers/layout/form"
    values:
        title_prefix: "ASP.NET MVC Form Component"
-
    scope:
        path: "html-helpers/layout/dialog"
    values:
        title_prefix: "ASP.NET MVC Dialog Component"
-
    scope:
        path: "html-helpers/layout/expansionpanel"
    values:
        title_prefix: "ASP.NET MVC ExpansionPanel Component"
        title: "ExpansionPanel"
-
    scope:
        path: "html-helpers/layout/notification"
    values:
        title_prefix: "ASP.NET MVC Notification Component"
-
    scope:
        path: "html-helpers/layout/popover"
    values:
        title_prefix: "ASP.NET MVC PopOver Component"
-
    scope:
        path: "html-helpers/layout/popup"
    values:
        title_prefix: "ASP.NET MVC Popup Component"
-
    scope:
        path: "html-helpers/layout/responsivepanel"
    values:
        title_prefix: "ASP.NET MVC ResponsivePanel Component"
-
    scope:
        path: "html-helpers/layout/splitter"
    values:
        title_prefix: "ASP.NET MVC Splitter Component"
-
    scope:
        path: "html-helpers/layout/tilelayout"
    values:
        title_prefix: "ASP.NET MVC TileLayout Component"
-
    scope:
        path: "html-helpers/layout/tooltip"
    values:
        title_prefix: "ASP.NET MVC Tooltip Component"
-
    scope:
        path: "html-helpers/layout/window"
    values:
        title_prefix: "ASP.NET MVC Window Component"
-
    scope:
        path: "html-helpers/media/mediaplayer"
    values:
        title_prefix: "ASP.NET MVC MediaPlayer Component"
-
    scope:
        path: "html-helpers/media/scrollview"
    values:
        title_prefix: "ASP.NET MVC ScrollView Component"
-
    scope:
        path: "html-helpers/navigation/appbar"
    values:
        title_prefix: "ASP.NET MVC AppBar Component"
        title: "AppBar"
-
    scope:
        path: "html-helpers/navigation/bottomnavigation"
    values:
        title_prefix: "ASP.NET MVC AppBar BottomNavigation"
        title: "BottomNavigation"

    scope:
        path: "html-helpers/navigation/breadcrumb"
    values:
        title_prefix: "ASP.NET MVC Breadcrumb Component"
        title: "Breadcrumb"
-
    scope:
        path: "html-helpers/navigation/floatingactionbutton"
    values:
        title_prefix: "ASP.NET MVC FloatingActionButton Component"
-
    scope:
        path: "html-helpers/navigation/stepper"
    values:
        title_prefix: "ASP.NET MVC Stepper Component"
-
    scope:
        path: "html-helpers/navigation/wizard"
    values:
        title_prefix: "ASP.NET MVC Wizard Component"
-
    scope:
        path: "html-helpers/navigation/button"
    values:
        title_prefix: "ASP.NET MVC Button Component"
-
    scope:
        path: "html-helpers/navigation/buttongroup"
    values:
        title_prefix: "ASP.NET MVC ButtonGroup Component"
-
    scope:
        path: "html-helpers/navigation/drawer"
    values:
        title_prefix: "ASP.NET MVC Drawer Component"
-
    scope:
        path: "html-helpers/navigation/menu"
    values:
        title_prefix: "ASP.NET MVC Menu Component"
-
    scope:
        path: "html-helpers/navigation/actionsheet"
    values:
        title_prefix: "ASP.NET MVC ActionSheet Component"
-
    scope:
        path: "html-helpers/navigation/panelbar"
    values:
        title_prefix: "ASP.NET MVC PanelBar Component"
-
    scope:
        path: "html-helpers/navigation/radiobutton"
    values:
        title_prefix: "ASP.NET MVC RadioButton Component"
-
    scope:
        path: "html-helpers/navigation/tabstrip"
    values:
        title_prefix: "ASP.NET MVC TabStrip Component"
-
    scope:
        path: "html-helpers/navigation/timeline"
    values:
        title_prefix: "ASP.NET MVC TimeLine Component"
-
    scope:
        path: "html-helpers/navigation/toolbar"
    values:
        title_prefix: "ASP.NET MVC ToolBar Component"
-
    scope:
        path: "html-helpers/navigation/treeview"
    values:
        title_prefix: "ASP.NET MVC TreeView Component"
-
    scope:
        path: "html-helpers/pdf/pdfviewer"
    values:
        title_prefix: "ASP.NET MVC PDFViewer Component"
-
    scope:
        path: "html-helpers/scheduling/calendar"
    values:
        title_prefix: "ASP.NET MVC Calendar Component"
-
    scope:
        path: "html-helpers/scheduling/gantt"
    values:
        title_prefix: "ASP.NET MVC Gantt Component"
-
    scope:
        path: "html-helpers/scheduling/multiviewcalendar"
    values:
        title_prefix: "ASP.NET MVC MultiViewCalendar Component"
-
    scope:
        path: "html-helpers/scheduling/scheduler"
    values:
        title_prefix: "ASP.NET MVC Scheduler Component"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

# The google services configuration
google_tag_manager: GTM-6X92
gcs_engine: '001595215763381649090:rdwxfmavt8o'
gcs_api_key: 'AIzaSyDnvT29LoZiLUcywskEgTTum7j5pkx6s8I'

core: false
mvc: true

footer:
-
  title: "Getting Started"
  links:
    "Getting Started": https://docs.telerik.com/aspnet-mvc/getting-started/first-steps
    "Demos": https://demos.telerik.com/aspnet-mvc/
    "Sample Applications": https://demos.telerik.com/aspnet-mvc/
-
  title: "Support Resources"
  links:
    "Knowledge Base": https://docs.telerik.com/aspnet-mvc/knowledge-base
-
  title: "Community"
  links:
    "Forums": https://www.telerik.com/forums/aspnet-mvc
    "Blogs": https://www.telerik.com/blogs/.net
    "Feedback Portal": https://feedback.telerik.com/aspnet-mvc


download: https://www.telerik.com/download/aspnet-mvc
