# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/aspnet-core"

all_pages_domain: "https://docs.telerik.com"

capital_casing_redirects: true

# Exclude files which should not be in the output
exclude: [README.md, Gemfile, Gemfile.lock,api_sort.rb, Dockerfile, bs-config.js, build-docs.sh, copy_content.sh, copy_local.sh, docs-watcher/*, exclude_files.txt, install-npm.sh, start-docs.sh, watch.sh]
exclude_navigation: ["knowledge-base/*",api/Kendo.Mvc/*,api/Kendo.Mvc.UI/*,api/Kendo.Mvc.UI.Fluent/*]
navigation:

## List your directory names and order here, like this:

     "knowledge-base":
        title: "Knowledge Base"
        position: 280
     "api":
        title: "API Reference"
        position: 0
     "getting-started":
        title: "Getting Started"
        position: 2
     "getting-started/prerequisites":
        title: "Prerequisites"
        position: 4
     "getting-started/installation":
        title: "Download and Installation"
        position: 5
     "getting-started/helper-basics":
        title: "Working with Helpers"
        position: 6
     "getting-started/vs-integration":
        title: "Integrating with VS"
        position: 7
     "getting-started/scripts":
        title: "Helper Script Dependencies"
        position: 8
     "html-helpers":
        title: "Html Helpers"
        position: 3
     "tag-helpers":
        title: "Tag Helpers"
        position: 4
     "tag-helpers/datasource":
        title: "Data Source"
        position: 1
     "tag-helpers/data-management":
        title: "Data Management"
        position: 2
     "tag-helpers/data-management/grid":
        title: "Grid"
        position: 1
     "tag-helpers/data-management/pivotgrid":
        title: "PivotGrid"
        position: 2
     "tag-helpers/editors":
        title: "Editors"
        position: 3
     "tag-helpers/charts":
        title: "Charts"
        position: 4
     "tag-helpers/charts/treemap":
        title: "TreeMap"
        position: 2
     "tag-helpers/gauges":
        title: "Gauges"
        position: 5
     "tag-helpers/barcodes":
        title: "Barcodes"
        position: 6
     "tag-helpers/diagrams-and-maps":
        title: "Diagrams and Maps"
        position: 7
     "tag-helpers/scheduling":
        title: "Scheduling"
        position: 8
     "tag-helpers/layout":
        title: "Layout"
        position: 9
     "tag-helpers/navigation":
        title: "Navigation"
        position: 10
     "tag-helpers/conversational-ui":
        title: "Conversational UI"
        position: 11
        isNew: true
     "tag-helpers/conversational-ui/chat":
        title: "Chat"
     "tag-helpers/interactivity":
        title: "Interactivity and UX"
        position: 12
     "tag-helpers/media":
        title: "Media"
        position: 13
     "tag-helpers/pdf":
        title: "PDF"
        position: 14
     "tag-helpers/pdf/pdfviewer":
        title: "PDFViewer"
     "html-helpers/datasource":
        title: "Data Source"
        position: 1
     "html-helpers/data-management":
        title: "Data Management"
        position: 2
     "html-helpers/data-management/grid":
        title: "Grid"
     "html-helpers/data-management/grid/binding":
        title: "Data Binding"
        position: 2
     "html-helpers/data-management/grid/editing":
        title: "Editing"
        position: 3
     "html-helpers/data-management/grid/templates":
        title: "Templates"
        position: 9
     "html-helpers/data-management/listview/globalization":
        title: "Globalization"
        position: 40
     "html-helpers/data-management/listview/accessibility":
        title: "Accessibility"
        position: 50
     "html-helpers/data-management/pivotgrid":
        title: "PivotGrid"
     "html-helpers/data-management/spreadsheet/import-and-export-data":
        title: "Import and Export of Data"
     "html-helpers/data-management/spreadsheet/end-user":
        title: "End-User Documentation"
     "html-helpers/editors":
        title: "Editors"
        position: 3
     "html-helpers/editors/datetimepicker/globalization":
        title: "Globalization"
        position: 40
     "html-helpers/editors/datetimepicker/accessibility":
        title: "Accessibility"
        position: 50
     "html-helpers/editors/flatcolorpicker":
        title: "FlatColorPicker"
     "html-helpers/editors/datepicker/accessibility":
        title: "Accessibility"
        position: 50
     "html-helpers/charts":
        title: "Charts"
        position: 4
     "html-helpers/charts/chart-types":
        title: "Chart Types"
        position: 3
     "html-helpers/charts/stockchart":
        title: "StockChart"
        position: 4
     "html-helpers/charts/treemap":
        title: "TreeMap"
        position: 5
     "html-helpers/gauges":
        title: "Gauges"
        position: 5
     "html-helpers/barcodes":
        title: "Barcodes"
        position: 6
     "html-helpers/diagrams-and-maps":
        title: "Diagrams and Maps"
        position: 7
     "html-helpers/scheduling":
        title: "Scheduling"
        position: 8
     "html-helpers/layout":
        title: "Layout"
        position: 9
     "html-helpers/navigation":
        title: "Navigation"
        position: 10
     "html-helpers/navigation/radiobutton":
        title: "RadioButton"
     "html-helpers/navigation/menu/binding":
        title: "Binding"
        position: 2
     "html-helpers/navigation/menu/contextmenu":
        title: "ContextMenu"
        position: 3
     "html-helpers/conversational-ui":
        title: "Conversational UI"
        position: 11
        isNew: true
     "html-helpers/conversational-ui/chat":
        title: "Chat"
     "html-helpers/interactivity":
        title: "Interactivity and UX"
        position: 12
     "html-helpers/media":
        title: "Media"
        position: 13
     "html-helpers/pdf":
        title: "PDF"
        position: 14
     "html-helpers/pdf/pdfviewer":
        title: "PDFViewer"
     "html-helpers/scheduling/scheduler/binding":
        title: "Binding"
        position: 2
     "accessibility":
        title: "Accesibility"
        position: 6
     "backwards-compatibility":
        title: "Breaking Changes"
        position: 7

## List helpers directory names and order here, like this:
     "*appearance":
        title: "Appearance"
     "*binding":
        title: "Binding"
        position: 2
     "*troubleshoot":
        title: "Troubleshooting"
     "*editing":
        title: "Editing"
     "*export":
        title: "Export"
     "*filtering":
        title: "Filtering"
     "*integration":
        title: "Integration"
     "*selection":
        title: "Selection"
     "*state":
        title: "State Management"
     "*how-to":
        title: "How To"
     "*grid":
        title: "Grid"
     "*drawer":
        title: "Drawer"
        isNew: true
     "*listview":
        title: "ListView"
     "*treelist":
        title: "TreeList"
     "*spreadsheet":
        title: "Spreadsheet"
     "*arcgauge":
        title: "ArcGauge"
     "*autocomplete":
        title: "AutoComplete"
     "*barcode":
        title: "BarCode"
     "*button":
        title: "Button"
     "*buttongroup":
        title: "ButtonGroup"
     "html-helpers/scheduling/calendar":
        title: "Calendar"
     "html-helpers/scheduling/multiviewcalendar":
        title: "MultiViewCalendar"
     "tag-helpers/scheduling/multiviewcalendar":
        title: "MultiViewCalendar"
     "*colorpalette":
        title: "ColorPalette"
     "*colorpicker":
        title: "ColorPicker"
     "*/multicolumncombobox":
        isNew: true
        title: "MultiColumnComboBox"
     "*combobox":
        title: "ComboBox"
     "*dateinput":
        title: "DateInput"
     "*datepicker":
        title: "DatePicker"
     "*daterangepicker":
        title: "DateRangePicker"
     "*datetimepicker":
        title: "DateTimePicker"
     "*dialog":
        title: "Dialog"
     "*draganddrop":
        title: "DragAndDrop"
     "*dropdownlist":
        title: "DropDownList"
     "*dropdowntree":
        isNew: true
        title: "DropDownTree"
     "*editor":
        title: "Editor"
     "*flatcolorpicker":
        title: "FlatColorPicker"
     "*gantt":
        title: "Gantt"
     "*lineargauge":
        title: "LinearGauge"
     "*listbox":
        title: "ListBox"
     "*map":
        title: "Map"
     "*maskedtextbox":
        title: "MaskedTextBox"
     "*mediaplayer":
        title: "MediaPlayer"
     "*menu":
        title: "Menu"
     "*multiselect":
        title: "MultiSelect"
     "*notification":
        title: "Notification"
     "*popup":
        title: "Popup"
     "*numerictextbox":
        title: "NumericTextBox"
     "*rating":
        title: "Rating"
     "*progressbar":
        title: "ProgressBar"
     "*qrcode":
        title: "QRCode"
     "*/radiobutton":
        title: "RadioButton"
     "*radialgauge":
        title: "RadialGauge"
     "*rangeslider":
        title: "RangeSlider"
     "*responsivepanel":
        title: "ResponsivePanel"
     "*panelbar":
        title: "PanelBar"
     "*pivotgrid":
        title: "PivotGrid"
     "*scheduler":
        title: "Scheduler"
     "*scrollview":
        title: "ScrollView"
     "*slider":
        title: "Slider"
     "*sortable":
        title: "Sortable"
     "*splitter":
        title: "Splitter"
     "*stockchart":
        title: "StockChart"
     "*tabstrip":
        title: "TabStrip"
     "*timepicker":
        title: "TimePicker"
     "*tooltip":
        title: "Tooltip"
     "*toolbar":
        title: "ToolBar"
     "*treelist":
        title: "TreeList"
     "*treeview":
        title: "TreeView"
     "*treemap":
        title: "TreeMap"
     "*upload":
        title: "Upload"
     "*validator":
        title: "Validator"
     "*window":
        title: "Window"
     "*templates":
        title: "Templates"
     "*switch":
        title: "Switch"
     "*/accessibility":
        title: "Accessibility"

## The application virtual path
baseurl: /aspnet-core

## The Kendo UI version used
cdnVersion: "2019.1.115"

## The MVC Core version used
mvcCoreVersion: "2019.1.115"

ff-sheet-id: 1mottKpkbJFxkUq6rS3CsPrT8JQOE2JlUtsJBR622cxs

## Product
product: "Telerik UI for ASP.NET Core"
platform: aspnet-core

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"
        product: "aspnet-core"
        editable: true
-
    scope:
        path: "aspnet-core"
    values:
        product: "aspnet-core"

    scope:
        path: "api"
    values:
        editable: false
        res_type: api
        kind: api

type_links:
    "kendo.Class": "/api/javascript/class"
    "kendo.data.DataSource": "/api/javascript/data/datasource"
    "Array": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array"
    "Blob": "https://developer.mozilla.org/en/docs/Web/API/Blob"
    "File": "https://developer.mozilla.org/en-US/docs/Web/API/File"
    "Boolean": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean"
    "Function": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function"
    "jQuery": "http://api.jquery.com/Types/#jQuery"
    "Promise": "http://api.jquery.com/Types/#Promise"
    "Object": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object"
    "Number": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number"
    "String": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

# The google services configuration
google_tag_manager: GTM-6X92
gcs_engine: '001595215763381649090:rfbgc0yrusm'
gcs_api_key: 'AIzaSyCkef2O-98IZGc0Jv16ozv8gqL-r1mL2_0'

has_web_api_index: true
skip_tabbed_code: true
code_lang: true
has_kb_portal: true
api_columns_count: 2
edit_repo_url: https://github.com/telerik/kendo-ui-core/edit/master/docs-aspnet-core
download: https://www.telerik.com/download-trial-file/v2/aspnet-core-ui
nav:
  "Demos": http://demos.telerik.com/aspnet-core/
  "Release History": https://www.telerik.com/support/whats-new/aspnet-core-ui/release-history
  "About": http://www.telerik.com/aspnet-mvc/mvc6-features
  "Pricing": http://www.telerik.com/purchase/aspnet-core-ui

footer:
-
  title: "Getting Started"
  links:
    "Getting Started": https://docs.telerik.com/aspnet-core/getting-started/getting-started
    "Demos": https://demos.telerik.com/aspnet-core/
    "Sample Applications": https://demos.telerik.com/aspnet-core/
-
  title: "Support Resources"
  links:
    "Knowledge Base": https://docs.telerik.com/aspnet-core/knowledge-base
-
  title: "Community"
  links:
    "Forums": https://www.telerik.com/forums/aspnet-core-ui
    "Blogs": https://www.telerik.com/blogs/.net
    "Feedback Portal": https://feedback.telerik.com/aspnet-core-ui

footer_social:
    facebook: https://www.facebook.com/Telerik/
    youtube: https://www.youtube.com/user/TelerikInc
    linkedin: https://www.linkedin.com/showcase/telerik/
    twitter: https://twitter.com/Telerik/

# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier
    gzip: false

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
