# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/aspnet-core"

# Exclude files which should not be in the output
exclude: [readme.md, Gemfile, Gemfile.lock,api_sort.rb]
navigation:


## List your directory names and order here, like this:

     "api":
        title: "API Reference"
        position: 0
     "getting-started":
        title: "Getting Started"
        position: 2
     "html-helpers":
        title: "Html Helpers"
        position: 3
     "tag-helpers":
        title: "Tag Helpers"
        position: 4
     "tag-helpers/datasource":
        title: "Data Source"
        position: 1
     "tag-helpers/data-management":
        title: "Data Management"
        position: 2
     "tag-helpers/data-management/grid":
        title: "Grid"
        position: 1
     "tag-helpers/data-management/pivotgrid":
        title: "PivotGrid"
        position: 2
     "tag-helpers/editors":
        title: "Editors"
        position: 3
     "tag-helpers/charts":
        title: "Charts"
        position: 4
     "tag-helpers/charts/treemap":
        title: "TreeMap"
        position: 2
     "tag-helpers/gauges":
        title: "Gauges"
        position: 5
     "tag-helpers/barcodes":
        title: "Barcodes"
        position: 6
     "tag-helpers/diagrams-and-maps":
        title: "Diagrams and Maps"
        position: 7
     "tag-helpers/scheduling":
        title: "Scheduling"
        position: 8
     "tag-helpers/layout":
        title: "Layout"
        position: 9
     "tag-helpers/navigation":
        title: "Navigation"
        position: 10
     "tag-helpers/conversational-ui":
        title: "Conversational UI"
        position: 11
        isNew: true
     "tag-helpers/conversational-ui/chat":
        title: "Chat"
     "tag-helpers/interactivity":
        title: "Interactivity and UX"
        position: 12
     "tag-helpers/media":
        title: "Media"
        position: 13
     "html-helpers/data-management":
        title: "Data Management"
        position: 1
     "html-helpers/data-management/grid":
        title: "Grid"
     "html-helpers/data-management/pivotgrid":
        title: "PivotGrid"
     "html-helpers/editors":
        title: "Editors"
        position: 2
     "html-helpers/editors/flatcolorpicker":
        title: "FlatColorPicker"
     "html-helpers/charts":
        title: "Charts"
        position: 3
     "html-helpers/charts/treemap":
        title: "TreeMap"
        position: 2
     "html-helpers/gauges":
        title: "Gauges"
        position: 4
     "html-helpers/barcodes":
        title: "Barcodes"
        position: 5
     "html-helpers/diagrams-and-maps":
        title: "Diagrams and Maps"
        position: 6
     "html-helpers/scheduling":
        title: "Scheduling"
        position: 7
     "html-helpers/layout":
        title: "Layout"
        position: 8
     "html-helpers/navigation":
        title: "Navigation"
        position: 9
     "html-helpers/conversational-ui":
        title: "Conversational UI"
        position: 10
        isNew: true
     "html-helpers/conversational-ui/chat":
        title: "Chat"
     "html-helpers/interactivity":
        title: "Interactivity and UX"
        position: 11
     "html-helpers/media":
        title: "Media"
        position: 12
     "how-to":
        title: "How To"
        position: 5
     "vs-integration":
        title: "Visual Studio Integration"
        position: 6
     "backwards-compatibility":
        title: "Breaking Changes"
        position: 7

## List helpers directory names and order here, like this:
     "*appearance":
        title: "Appearance"
     "*binding":
        title: "Binding"
     "*troubleshoot":
        title: "Troubleshooting"
     "*editing":
        title: "Editing"
     "*export":
        title: "Export"
     "*filtering":
        title: "Filtering"
     "*integration":
        title: "Integration"
     "*selection":
        title: "Selection"
     "*state":
        title: "State Management"
     "*how-to":
        title: "How To"
     "*grid":
        title: "Grid"
     "*listview":
        title: "ListView"
     "*treelist":
        title: "TreeList"
     "*spreadsheet":
        title: "Spreadsheet"
     "*arcgauge":
        title: "ArcGauge"
     "*autocomplete":
        title: "AutoComplete"
     "*barcode":
        title: "BarCode"
     "*button":
        title: "Button"
     "*buttongroup":
        title: "ButtonGroup"
     "*calendar":
        title: "Calendar"
     "*colorpalette":
        title: "ColorPalette"
     "*colorpicker":
        title: "ColorPicker"
     "*combobox":
        title: "ComboBox"
     "*dateinput":
        title: "DateInput"
     "*datepicker":
        title: "DatePicker"
     "*datetimepicker":
        title: "DateTimePicker"
     "*dialog":
        title: "Dialog"
     "*draganddrop":
        title: "DragAndDrop"
     "*dropdownlist":
        title: "DropDownList"
     "*dropdowntree":
        isNew: true
        title: "DropDownTree"
     "*editor":
        title: "Editor"
     "*flatcolorpicker":
        title: "FlatColorPicker" 
     "*gantt":
        title: "Gantt"
     "*lineargauge":
        title: "LinearGauge"
     "*listbox":
        title: "ListBox"
     "*map":
        title: "Map"
     "*maskedtextbox":
        title: "MaskedTextBox"
     "*mediaplayer":
        title: "MediaPlayer"
     "*menu":
        title: "Menu"
     "*multiselect":
        title: "MultiSelect"
     "*notification":
        title: "Notification"
     "*popup":
        title: "Popup"
     "*numerictextbox":
        title: "NumericTextBox"
     "*progressbar":
        title: "ProgressBar"
     "*qrcode":
        title: "QRCode"
     "*radialgauge":
        title: "RadialGauge"
     "*rangeslider":
        title: "RangeSlider"
     "*responsivepanel":
        title: "ResponsivePanel"
     "*panelbar":
        title: "PanelBar"
     "*pivotgrid":
        title: "PivotGrid"
     "*scheduler":
        title: "Scheduler"
     "*slider":
        title: "Slider"
     "*sortable":
        title: "Sortable"
     "*splitter":
        title: "Splitter"
     "*stockchart":
        title: "StockChart"
     "*tabstrip":
        title: "TabStrip"
     "*timepicker":
        title: "TimePicker"
     "*tooltip":
        title: "Tooltip"
     "*toolbar":
        title: "ToolBar"
     "*treelist":
        title: "TreeList"
     "*treeview":
        title: "TreeView"
     "*treemap":
        title: "TreeMap"
     "*upload":
        title: "Upload"
     "*validator":
        title: "Validator"
     "*window":
        title: "Window"
     "*templates":
        title: "Templates"

## The application virtual path
baseurl: /aspnet-core

## The Kendo UI version used
cdnVersion: "2017.2.621"

## The MVC Core version used
mvcCoreVersion: "2017.2.621"

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "page"
        category: "default"
        product: "aspnet-core"
        editable: true
-
    scope:
        path: "aspnet-core"
    values:
        product: "aspnet-core"

    scope:
        path: "api"
    values:
        editable: false

type_links:
    "kendo.Class": "/api/javascript/class"
    "kendo.data.DataSource": "/api/javascript/data/datasource"
    "Array": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array"
    "Blob": "https://developer.mozilla.org/en/docs/Web/API/Blob"
    "File": "https://developer.mozilla.org/en-US/docs/Web/API/File"
    "Boolean": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean"
    "Function": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function"
    "jQuery": "http://api.jquery.com/Types/#jQuery"
    "Promise": "http://api.jquery.com/Types/#Promise"
    "Object": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object"
    "Number": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number"
    "String": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

# The google services configuration
google_tag_manager: GTM-6X92
google_custom_search: '001595215763381649090:rfbgc0yrusm'

# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier
    gzip: false

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
