# The public documentation URL, used for sitemap.xml
url: "http://docs.telerik.com/kendo-ui"

# Exclude files which should not be in the output
exclude: [readme.md, Gemfile, Gemfile.lock,api_sort.rb]
navigation:
## List your directory names and order here, like this:
    "api":
        title: "API Reference"
        position: 0
    "intro":
        title: "Getting Started"
        position: 2
    "intro/installation":
        title: "Prerequisites and Installation"
        position: 1
    "intro/supporting":
        title: "Additional Resources"
        position: 2
    "controls":
        title: "Widgets"
        position: 3
    "controls/data-management":
        title: "Data Management"
        position: 1
    "controls/data-management/grid/how-to/AngularJS":
        title: "AngularJS"
        position: 1
    "controls/data-management/grid/how-to/Editing":
        title: "Editing"
        position: 2
    "controls/data-management/grid/how-to/Layout":
        title: "Appearance"
        position: 3
    "controls/data-management/grid/how-to/Selection":
        title: "Selection"
        position: 4
    "controls/data-management/grid/how-to/Templates":
        title: "Templates"
        position: 5
    "controls/data-management/grid/how-to/excel":
        title: "Excel Export"
        position: 6
    "controls/data-management/grid/how-to/pdf-export":
        title: "PDF Export"
        position: 7
    "controls/editors":
        title: "Editors"
        position: 2
    "controls/charts":
        title: "Charts"
        position: 3
    "controls/charts/chart-types":
        title: "Chart Types"
        position: 9
    "controls/charts/stockchart":
        title: "Stock Charts"
        position: 10
    "controls/charts/sparkline":
        title: "Sparklines"
        position: 11
    "controls/charts/treemap":
        title: "TreeMap"
        position: 12
    "controls/gauges":
        title: "Gauges"
        position: 4
    "controls/barcodes":
        title: "Barcodes"
        position: 5
    "controls/diagrams-and-maps":
        title: "Diagrams and Maps"
        position: 6
    "controls/scheduling":
        title: "Scheduling"
        position: 7
    "controls/layout":
        title: "Layout"
        position: 8
    "controls/navigation":
        title: "Navigation"
        position: 9
    "controls/interactivity":
        title: "Interactivity and UX"
        position: 10
    "controls/interactivity/fx":
        title: "FX"
    "controls/interactivity/draganddrop":
        title: "Drag and Drop"
    "controls/hybrid":
        title: "Hybrd UI"
        position: 11
    "controls/hybrid/listview":
        title: "Mobile ListView"
        position: 9
    "controls/hybrid/collapsible":
        title: "Collapsible"
        position: 14
    "controls/hybrid/drawer":
        title: "Drawer"
    "controls/hybrid/forms":
        title: "Forms"
    "controls/hybrid/navbar":
        title: "NavBar"
    "controls/hybrid/scrollview":
        title: "ScrollView"
    "styles-and-layout":
        title: "Styles and Appearance"
        position: 13
    "framework":
        title: "Framework and Utilities"
        position: 15
    "framework/datasource":
        title: "DataSource"
        position: 1
    "framework/hierarchicaldatasource":
        title: "HierarchicalDataSource"
        position: 2
    "framework/mvvm":
        title: "MVVM"
        position: 3
    "framework/templates":
        title: "Templates"
        position: 4
    "framework/spa":
        title: "Single Page Applications"
        position: 5
    "framework/excel":
        title: "Create Excel Documents"
        position: 6
    "framework/drawing":
        title: "Drawing API"
        position: 7
    "framework/globalization":
        title: "Globalization"
        position: 8
    "framework/localization":
        title: "Localization"
        position: 9
    "framework/validator":
        title: "Validator"
        position: 10
    "framework/save-files":
        title: "Save Files"
        position: 11
    "framework/widgets":
        title: "Widgets"
        position: 12
    "third-party":
        title: "Third-Party Frameworks and Utilities"
        position: 16
    "third-party/tutorials":
        title: "Tutorials"
        position: 8
    "third-party/tutorials/webforms":
        title: "ASP.NET Web Forms"
        position: 1
    "AngularJS":
        title: "AngularJS Directives"
        position: 17
    "aspnet-mvc":
        title: "UI for ASP.NET MVC"
        position: 18
    "aspnet-mvc/mvc-6":
        title: "ASP.NET MVC 6"
        position: 4
    "aspnet-mvc/vs-integration":
        title: "Visual Studio Integration"
        position: 9
    "aspnet-mvc/migration":
        title: "Migrate From Telerik Extensions"
        position: 12
    "aspnet-mvc/helpers":
        title: "View Helpers"
        position: 11
    "aspnet-mvc/tutorial-saleshub":
        title: "Tutorial: Build the Sales Hub Project"
        position: 20
    "aspnet-mvc/tutorial-kendo-music-store":
        title: "Tutorial: Build the Kendo Music Store"
        position: 20
    "aspnet-mvc/tutorial-kendo-music-store/music-store-web":
        title: "Build the Web Application"
        position: 2
    "aspnet-mvc/tutorial-kendo-music-store/music-store-dashboard":
        title: "Build the Dashboard"
        position: 3
    "jsp":
        title: "UI for JSP"
        position: 19
    "php":
        title: "UI for PHP"
        position: 20
    "troubleshoot":
        title: "Troubleshooting"
        position: 22
    "accessibility":
        title: "Accessibility"
        position: 23
    "backwards-compatibility":
        title: "Backwards Compatibility"
        position: 24
    "backwards-compatibility/2012":
        title: "2012"
        position: 5
    "backwards-compatibility/2013":
        title: "2013"
        position: 4
    "backwards-compatibility/2014":
        title: "2014"
        position: 3
    "backwards-compatibility/2015":
        title: "2015"
        position: 2
    "backwards-compatibility/2016":
        title: "2016"
        position: 1
    "*how-to":
        title: "How To"
        position: 200
    "*angular":
        title: "AngularJS"
        position: 1
    "*troubleshoot":
        title: "Troubleshooting"
        position: 201
    "*asp.net":
        title: "ASP.NET"
    "*widgets":
        title: "Widgets"
    "*tags":
        title: "Tags"
    "*excel":
        title: "Excel"
    "*pdf-export":
        title: "PDF Export"
    "*mobileactionsheet":
        title: "MobileActionSheet"
    "*mobileapplication":
        title: "MobileApplication"
    "*mobilebuttongroup":
        title: "MobileButtonGroup"
    "*mobilelayout":
        title: "MobileLayout"
    "*mobilemodalview":
        title: "MobileModalView"
    "*mobilepopover":
        title: "MobilePopOver"
    "*mobilesplitview":
        title: "MobileSplitView"
    "*mobileswitch":
        title: "MobileSwitch"
    "*mobiletabstrip":
        title: "MobileTabStrip"
    "*mobilelistview":
        title: "MobileListView"
    "*mobileview":
        title: "MobileView"
    "*mobilebutton":
        title: "MobileButton"
    "*barcode":
        title: "Barcode"
    "*stockchart":
        title: "Stock Chart"
    "*chart":
        title: "Chart"
    "*chart-types":
        title: "Chart Types"
        position: 8
    "*dataviz":
        title: "Data Visualization"
    "*lineargauge":
        title: "LinearGauge"
    "*treemap":
        title: "TreeMap"
    "*qrcode":
        title: "QRCode"
    "*radialgauge":
        title: "RadialGauge"
    "*sparkline":
        title: "Sparkline"
    "*stockchart":
        title: "StockChart"
    "*map":
        title: "Map"
    "*diagram":
        title: "Diagram"
    "*hierarchicaldatasource":
        title: "HierarchicalDataSource"
    "*datasource":
        title: "DataSource"
    "*draganddrop":
        title: "Drag and Drop"
    "*fx":
        title: "FX"
    "*globalization":
        title: "Globalization"
    "*mvvm":
        title: "MVVM"
    "*spa":
        title: "SPA"
    "*templates":
        title: "Templates"
    "*validator":
        title: "Validator"
    "*autocomplete":
        title: "AutoComplete"
    "*button":
        title: "Button"
    "*calendar":
        title: "Calendar"
    "*colorpalette":
        title: "ColorPalette"
    "*flatcolorpicker":
        title: "FlatColorPicker"
    "*colorpicker":
        title: "ColorPicker"
    "*combobox":
        title: "ComboBox"
    "*datepicker":
        title: "DatePicker"
    "*datetimepicker":
        title: "DateTimePicker"
    "*dropdownlist":
        title: "DropDownList"
    "*editor":
        title: "Editor"
    "*gantt":
        title: "Gantt"
    "*pivotgrid":
        title: "PivotGrid"
    "*grid":
        title: "Grid"
    "*spreadsheet":
        title: "Spreadsheet"
    "*import-and-export-data":
        title: "Import and Export Data"
        position: 4
    "*localization-spreadsh":
        title: "Localization"
        position: 5
    "*end-user":
        title: "For the End User"
        position: 6
    "*listview":
        title: "ListView"
    "*maskedtextbox":
        title: "MaskedTextBox"
    "*menu":
        title: "Menu"
    "*multiselect":
        title: "MultiSelect"
    "*notification":
        title: "Notification"
    "*numerictextbox":
        title: "NumericTextBox"
    "*panelbar":
        title: "PanelBar"
    "*pivotdatasource":
        title: "PivotDataSource"
    "*pivotconfigurator":
        title: "PivotConfigurator"
    "*progressbar":
        title: "ProgressBar"
    "*rangeslider":
        title: "RangeSlider"
    "*responsivepanel":
        title: "ResponsivePanel"
    "*scheduler":
        title: "Scheduler"
    "*slider":
        title: "Slider"
    "*sortable":
        title: "Sortable"
    "*splitter":
        title: "Splitter"
    "*tabstrip":
        title: "TabStrip"
    "*timepicker":
        title: "TimePicker"
    "*tooltip":
        title: "Tooltip"
    "*toolbar":
        title: "ToolBar"
    "*treelist":
        title: "TreeList"
    "*treeview":
        title: "TreeView"
    "*upload":
        title: "Upload"
    "*window":
        title: "Window"
    "*hello-kendo-ui":
        title: "Hello Kendo UI"
    "*home-page":
        title: "Home Page"
    "*order-page":
        title: "Order Page"
    "*localization":
        title: "Localization"
    "aspnet-mvc/vs-integration":
        title: "Visual Studio Integration"
        position: 9
    "aspnet-mvc/migration":
        title: "Migrate From Telerik Extensions"
        position: 12
    "aspnet-mvc/helpers":
        title: "View Helpers"
        position: 11
    "aspnet-mvc/tutorial-saleshub":
        title: "Tutorial: Build the Sales Hub Project"
        position: 20
    "aspnet-mvc/tutorial-kendo-music-store":
        title: "Tutorial: Build the Kendo Music Store"
        position: 20
    "aspnet-mvc/tutorial-kendo-music-store/music-store-web":
        title: "Build the Web Application"
        position: 2
    "aspnet-mvc/tutorial-kendo-music-store/music-store-dashboard":
        title: "Build the Dashboard"
        position: 3
    "api/javascript":
        title: "JavaScript"
        position: 2
    "api/aspnet-mvc":
        title: "ASP.NET MVC"
        position: 3
    "api/jsp":
        title: "JSP"
        position: 4
    "api/php":
        title: "PHP"
        position: 5

## The application virtual path
baseurl: /kendo-ui

## The Kendo UI version used
cdnVersion: "2015.3.1111"

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "page"
        category: "default"
        product: "kendo-ui"
        editable: true
-
    scope:
        path: "aspnet-mvc"
    values:
        product: "aspnet-mvc"
-
    scope:
        path: "api/aspnet-mvc"
    values:
        product: "aspnet-mvc"
        editable: false
-
    scope:
        path: "php"
    values:
        product: "php-ui"
-
    scope:
        path: "api/php"
    values:
        product: "php-ui"
        editable: false
-
    scope:
        path: "api/jsp"
    values:
        product: "jsp-ui"
        editable: false
-
    scope:
        path: "jsp"
    values:
        product: "jsp-ui"
-
    scope:
        path: "api"
    values:
        kind: "api"
-
    scope:
        path: "api/javascript"
    values:
        editableExample: "true"

type_links:
    "kendo.Class": "/api/javascript/class"
    "kendo.data.DataSource": "/api/javascript/data/datasource"
    "Array": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array"
    "Blob": "https://developer.mozilla.org/en/docs/Web/API/Blob"
    "File": "https://developer.mozilla.org/en-US/docs/Web/API/File"
    "Boolean": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean"
    "Function": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function"
    "jQuery": "http://api.jquery.com/Types/#jQuery"
    "Promise": "http://api.jquery.com/Types/#Promise"
    "Object": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object"
    "Number": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number"
    "String": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

# The google services configuration
google_tag_manager: GTM-6X92
google_custom_search: '001595215763381649090:eblhnfskwrk'

# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
