# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/aspnet-mvc"

all_pages_domain: "https://docs.telerik.com"

capital_casing_redirects: true

# Exclude files which should not be in the output
exclude: [README.md, Gemfile, Gemfile.lock,api_sort.rb, Dockerfile, bs-config.js, build-docs.sh, copy_content.sh, copy_local.sh, docs-watcher/*, exclude_files.txt, install-npm.sh, start-docs.sh, watch.sh]
exclude_navigation: [asp-net-mvc-3.html,asp-net-mvc-4.html,api/Kendo.Mvc/*,api/Kendo.Mvc.UI/*,api/Kendo.Mvc.UI.Fluent/*]
navigation:
## List your directory names and order here, like this:

     "api":
        title: "API Reference"
        position: 0
     "getting-started":
        title: "Getting Started"
        position: 3
     "helpers":
        title: "Widgets"
        position: 4
     "vs-integration":
        title: "Visual Studio Integration"
        position: 5
     "migration":
        title: "Migration"
        position: 6
     "styles-and-layout":
        title: "Styles and Appearance"
        position: 7
     "how-to":
        title: "How To"
        position: 8
     "tutorials":
        title: "Tutorials"
        position: 9
     "troubleshoot":
        title: "Troubleshooting"
        position: 10



## List helpers directory names and order here, like this:
     "helpers/autocomplete":
        title: "AutoComplete"
     "helpers/barcode":
        title: "Barcode"
     "helpers/button":
        title: "Button"
     "helpers/calendar":
        title: "Calendar"
     "helpers/chart":
        title: "Chart"
     "helpers/chat":
        title: "Chat"
        isNew: true
     "helpers/colorpalette":
        title: "ColorPalette"
     "helpers/colorpicker":
        title: "ColorPicker"
     "helpers/multicolumncombobox":
        title: "MultiColumnComboBox"
     "helpers/combobox":
        title: "ComboBox"
     "helpers/dateinput":
        title: "DateInput"
     "helpers/datepicker":
        title: "DatePicker"
     "helpers/daterangepicker":
        title: "DateRangePicker"		
     "helpers/datetimepicker":
        title: "DateTimePicker"
     "helpers/diagram":
        title: "Diagram"
     "helpers/dialog":
        title: "Dialog"
     "helpers/dropdownlist":
        title: "DropDownList"
     "helpers/dropdowntree":
        isNew: true
        title: "DropDownTree"
     "helpers/editor":
        title: "Editor"
     "helpers/flatcolorpicker":
        title: "FlatColorPicker"
     "helpers/gantt":
        title: "Gantt"
     "helpers/grid":
        title: "Grid"
     "helpers/grid/binding":
        title: "Binding"
        position: 6
     "helpers/grid/editing":
        title: "Editing"
        position: 7
     "helpers/grid/templating":
        title: "Templates"
        position: 8
     "helpers/grid/how-to":
        title: "How To"
        position: 9
     "helpers/grid/troubleshoot":
        title: "Troubeshooting"
        position: 10
     "*appearance":
        title: "Appearance"
     "*binding":
        title: "Binding"
     "*troubleshoot":
        title: "Troubleshooting"
     "*editing":
        title: "Editing"
     "*export":
        title: "Export"
     "*filtering":
        title: "Filtering"
     "*integration":
        title: "Integration"
     "*selection":
        title: "Selection"
     "*state":
        title: "State Management"
     "*how-to":
        title: "How To"
     "helpers/hybrid":
        title: "Hybrid"
     "*mobileactionsheet":
        title: "ActionSheet"
     "*mobileapplication":
        title: "Application"
     "*mobilebutton":
        title: "Button"
     "*mobilebuttongroup":
        title: "ButtonGroup"
     "*mobiledrawer":
        title: "Drawer"
     "*mobilelayout":
        title: "Layout"
     "*mobilelistview":
        title: "ListView"
     "*mobilemodalview":
        title: "ModalView"
     "*mobilenavbar":
        title: "NavBar"
     "*mobilepopover":
        title: "PopOver"
     "*mobilescrollview":
        title: "ScrollView"
     "*mobilesplitview":
        title: "SplitView"
     "*mobileswitch":
        title: "Switch"
     "*mobiletabstrip":
        title: "TabStrip"
     "*mobileview":
        title: "View"
     "helpers/lineargauge":
        title: "LinearGauge"
     "helpers/listview":
        title: "ListView"
     "helpers/listbox":
        title: "ListBox"
     "helpers/map":
        title: "Map"
     "helpers/maskedtextbox":
        title: "MaskedTextBox"
     "helpers/mediaplayer":
        title: "MediaPlayer"
     "helpers/menu":
        title: "Menu"
     "helpers/multiselect":
        title: "MultiSelect"
     "helpers/multiviewcalendar":
        title: "MultiViewCalendar"
     "helpers/notification":
        title: "Notification"
     "helpers/numerictextbox":
        title: "NumericTextBox"
     "helpers/panelbar":
        title: "PanelBar"
     "helpers/pivotgrid":
        title: "PivotGrid"
     "helpers/progressbar":
        title: "ProgressBar"
     "helpers/qrcode":
        title: "QRCode"
     "*arcgauge":
        title: "ArcGauge"
     "helpers/radialgauge":
        title: "RadialGauge"
     "helpers/radiobutton":
        title: "RadioButton"
     "helpers/scheduler":
        title: "Scheduler"
     "helpers/scrollview":
        title: "ScrollView"
     "helpers/slider":
        title: "Slider"
     "helpers/sortable":
        title: "Sortable"
     "helpers/splitter":
        title: "Splitter"
     "helpers/spreadsheet":
        title: "SpreadSheet"
     "helpers/stockchart":
        title: "StockChart"
     "helpers/switch":
        title: "Switch"
     "helpers/tabstrip":
        title: "TabStrip"
     "helpers/timepicker":
        title: "TimePicker"
     "helpers/toolbar":
        title: "ToolBar"
     "helpers/tooltip":
        title: "Tooltip"
     "helpers/treelist":
        title: "TreeList"
     "helpers/treemap":
        title: "TreeMap"
     "helpers/treeview":
        title: "TreeView"
     "helpers/upload":
        title: "Upload"
     "helpers/window":
        title: "Window"

## List migration directory names and order here, like this:
     "migration/widgets":
        title: "Widgets"
        position: 2

## List tutorials directory names and order here, like this:
     "tutorials/quickstart":
        title: "Quick Start"
        position: 1
     "tutorials/tutorial-kendo-music-store":
        title: "Tutorial Kendo Music Store"
        position: 2
     "tutorials/tutorial-kendo-music-store/music-store-dashboard":
        title: "Music Store Dashboard"
        position: 2
     "tutorials/tutorial-kendo-music-store/music-store-web":
        title: "Music Store Web"
        position: 3
     "tutorials/tutorial-saleshub":
        title: "Tutorial Sales Hub"
        position: 3
     "tutorials/tutorial-saleshub/home-page":
        title: "Home Page"
        position: 2
     "tutorials/tutorial-saleshub/order-page":
        title: "Order Page"
        position: 3

## The application virtual path
baseurl: /aspnet-mvc

## The Kendo UI version used
cdnVersion: "2019.1.115"

## The MVC Core version used
mvcCoreVersion: "2019.1.115"

ff-sheet-id: 17DDhsKyPUgO6GlvL8WEfCCN6tikyInp4qpRGCvvs794

## Product
product: "Telerik UI for ASP.NET MVC"
platform: aspnet-mvc

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"
        product: "aspnet-mvc"
        editable: true
-
    scope:
        path: "aspnet-mvc"
    values:
        product: "aspnet-mvc"

    scope:
        path: "api"
    values:
        editable: false
        res_type: api
        kind: api

type_links:
    "kendo.Class": "/api/javascript/class"
    "kendo.data.DataSource": "/api/javascript/data/datasource"
    "Array": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array"
    "Blob": "https://developer.mozilla.org/en/docs/Web/API/Blob"
    "File": "https://developer.mozilla.org/en-US/docs/Web/API/File"
    "Boolean": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean"
    "Function": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function"
    "jQuery": "http://api.jquery.com/Types/#jQuery"
    "Promise": "http://api.jquery.com/Types/#Promise"
    "Object": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object"
    "Number": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number"
    "String": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

# The google services configuration
google_tag_manager: GTM-6X92
gcs_engine: '001595215763381649090:rdwxfmavt8o'
gcs_api_key: 'AIzaSyDnvT29LoZiLUcywskEgTTum7j5pkx6s8I'

has_web_api_index: true
skip_tabbed_code: true
code_lang: true
api_columns_count: 2
edit_repo_url: https://github.com/telerik/kendo-ui-core/edit/master/docs-aspnet-mvc

download: http://www.telerik.com/download/aspnet-mvc

footer_social:
    facebook: https://www.facebook.com/Telerik/
    youtube: https://www.youtube.com/user/TelerikInc
    linkedin: https://www.linkedin.com/showcase/telerik/
    twitter: https://twitter.com/Telerik/


# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier
    gzip: false

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
